matrix:
  include:
    - language: java
      sudo: false
      jdk:
        - openjdk8
      script:
      install: 
        - skip
      os: 
        - linux
      dist: 
        - trusty
      script:
        - echo 'Going into java folder'
        - cd webapp-java
        - echo 'Setting up permissions'
        - git update-index --chmod=+x gradlew
        - chmod +x gradlew
        - git ls-tree HEAD
        - echo 'Building'
        - travis_wait 50 ./gradlew build  
    - language: csharp
      solution: webapp-net/DxaModules.sln            
