// Dynamic Documentation GUI build pipeline
pipeline {

    agent {
        label 'dxadocker'
    }

    stages {
        stage('Building DD GUI') {
            steps {
                dir("gui") {
                    powershell 'mvn clean package'
                }
            }
        }
    }

    post {
        always {
            dir("gui") {
                archiveArtifacts artifacts: 'target/gui/**', fingerprint: true
            }
        }
    }
}

