using System.Reflection;

#if TRIDION_71
    [assembly: AssemblyTitle("SDL DXA Audience Manager Module for 2013 SP1")]
#else
    [assembly: AssemblyTitle("SDL DXA Audience Manager Module for SDL Web 8")]
#endif

// NOTE: Common Assembly Info is generated by the build in CommonAssemblyInfo.cs
