// Dynamic Documentation GUI build pipeline
pipeline {

    agent {
        label 'dxadocker'
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds()
    }

    parameters {
        string name: "tempFolder", defaultValue: "C:\\Temp\\DXA\\DDGUIBoilerplate", description: 'Temporary folder'
        string name: "packageName", defaultValue: 'Sdl.Dxa.Modules.DynamicDocumentation.Boilerplate', description: 'Name of the package we are going to publish'
        string name: "version", defaultValue: '2.2.1', description: 'Version of the package we are going to publish'
        booleanParam name: "isPreRelease", defaultValue: true, description: "If we add 'beta' prefix to the version"
    }

    stages {
        stage('Building DD GUI Boilerplate') {
            when { not {
                branch 'develop'
            } }
            steps {
                dir("boilerplate") {
                    powershell 'mvn -B clean package'
                }
            }
        }

        stage('Building and publishing DD GUI Boilerplate') {
            when {
                branch 'develop'
            }
            steps {
                dir("boilerplate") {
                    powershell 'mvn -B -Psonatype-nexus-snapshots clean deploy'
                }
            }
        }

        stage('Publishing Dynamic Documentation Module GUI Boilerplate NuGet Package') {
            when {
                branch 'develop'
            }
            steps {
                dir("boilerplate/nuget") {
                    powershell ".\\publish.ps1 -guiSourcePath '..\\' -tempFolder '${tempFolder}' -Actions @('Prepare', 'Push') -packageName '${packageName}' -version '${version}' -isPreRelease ('${isPreRelease}' -eq 'true')"
                }
            }
        }
    }

    post {
        always {
            dir("boilerplate") {
                archiveArtifacts artifacts: 'target/**', fingerprint: true
            }
        }
    }
}

