name: build_GUI

on:
  push:
    branches: [ develop, release/2.2, release/1.8 ]
  pull_request:
    branches: [ develop, release/2.2, release/1.8 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout...
      uses: actions/checkout@v2
    - name: Preparing NPM...
      run:
        cd gui;
        sudo npm install;
        sudo npm install -g;
        sudo chown -R $USER:$(id -gn $USER) /home/runner/.config;
    - name: Building GUI...
      run:
        cd gui;
        sudo mvn -B clean install --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
