name: build_GUI

on:
  push:
    branches: [ develop, release/2.2, release/1.8 ]
  pull_request:
    branches: [ develop, release/2.2, release/1.8 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout...
      uses: actions/checkout@v2
    - name: Installing GULP...
      working-directory: gui
      run:        
        npm install --save-dev gulp;      
        gulp --version;
    - name: Preparing NPM...
      working-directory: gui
      run:
        sudo chown -R $USER /usr/local/lib/node_modules;
        npm install -g;
    - name: Building GUI...
      working-directory: gui
      run:
        mvn clean install --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
