name: build_GUI

on:
  push:
    branches: [ develop, release/2.2, release/1.8 ]
  pull_request:
    branches: [ develop, release/2.2, release/1.8 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout...
      uses: actions/checkout@v2
    - name: Installing GULP & DITA-OT...
      working-directory: gui
      run:        
        sudo npm install --save-dev gulp;
        yarn;
        gulp --version;
        cd node_modules;
        cd dita-ot;
        ./gradlew;
    - name: Preparing NPM...
      working-directory: gui
      run:        
        sudo chown -R $USER /usr/local/lib/node_modules;
        sudo npm install -g npm@latest;
        rm -rf node_modules;
        sudo npm install;
    - name: Building GUI...
      working-directory: gui
      run:
        mvn -B clean install --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
