name: build_GUI

on:
  push:
    branches: [ develop, release/2.2, release/1.8 ]
  pull_request:
    branches: [ develop, release/2.2, release/1.8 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout...
      uses: actions/checkout@v2
    - name: Preparing NPM...
      run:
        cd gui;
        mkdir ~/.npm-global;
        npm config set prefix '~/.npm-global';
        export PATH=~/.npm-global/bin:$PATH;
        source ~/.profile;
        npm install -g jshint;
        sudo chown -R $USER ~/.npm-global;
    - name: Building GUI...
      run:
        cd gui;
        mvn -B clean install --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
