name: javabuild

on:
  push:
    branches: [ develop, release/2.2, release/1.8 ]
  pull_request:
    branches: [ develop, release/2.2, release/1.8 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout...
      uses: actions/checkout@v2
    - name: 2. Setting permissions...
      run: 
        sudo chown -R runner:runner /usr/local/lib/node_modules;
        chmod a+w /usr/local/lib/node_modules;
    - name: 3. Going to GUI...
      run: 
        cd gui;
        ls -la;
    - name: 4. Installing NPM...
      run:        
        npm install -g;
    - name: 5. Building GUI...
      run:
        mvn -B clean install --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
    - name: 6. Building Web application...
      run:
        cd ../webapp-java;
        mvn -B clean install --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
