name: javabuild

on:
  push:
    branches: [ develop, release/2.2, release/1.8 ]
  pull_request:
    branches: [ develop, release/2.2, release/1.8 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout...
      uses: actions/checkout@v2
    - name: Installing NPM...
      run: 
        cd gui;
        ls -la /usr/local/lib/node_modules;
        chmod a+w /usr/local/lib/node_modules;
        npm install;
        npm install -g;
    - name: Building GUI...
      run:         
        mvn -B clean install --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
    - name: Building Web application...
      run: 
        cd ../webapp-java;
        mvn -B clean install --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
