name: build_java

on:
  push:
    branches: [ release/1.8 ]
  pull_request:
    branches: [ release/1.8 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout...
      uses: actions/checkout@v2
    - name: Building Web application...
      working-directory: webapp-java
      run:
        chmod +x gradlew;
        ./gradlew;
