name: javabuild

on:
  push:
    branches: [ develop, release/2.2, release/1.8 ]
  pull_request:
    branches: [ develop, release/2.2, release/1.8 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout...
      uses: actions/checkout@v2
    - name: 2. Setting permissions...
      run: 
        sudo chown -R runner:docker /usr/local/lib/node_modules;
        chmod a+w /usr/local/lib/node_modules;
    - name: 3. Building GUI...
      run:
        cd ../gui;
        mvn -B clean install --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
    - name: 4. Building Web application...
      run:
        cd ../webapp-java;
        mvn -B clean install --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
